package com.anish.banking.bank.stress;

import com.anish.banking.bank.auth.model.User;
import com.anish.banking.bank.auth.repository.UserRepository;
import com.anish.banking.bank.auth.security.JwtService;
import com.anish.banking.bank.ledger.account.model.Account;
import com.anish.banking.bank.ledger.account.repository.AccountRepository;
import com.anish.banking.bank.ledger.account.service.BalanceService;
import com.anish.banking.bank.ledger.ledger.model.EntryType;
import com.anish.banking.bank.ledger.ledger.model.LedgerEntry;
import com.anish.banking.bank.ledger.ledger.repository.LedgerEntryRepository;
import com.anish.banking.bank.ledger.transfer.dto.CreateTransferRequest;
import com.anish.banking.bank.ledger.transfer.dto.TransferResponse;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Reproducible evidence for the README claim "validated N transfers with zero duplicate
 * postings" (see docs/transfer-stress-test-report.md, regenerated by this test on every run).
 *
 * Exercises the REAL path end to end: a real embedded servlet container (RANDOM_PORT), real
 * HTTP requests (java.net.http.HttpClient) through JwtAuthFilter / RateLimitFilter /
 * TransferController / TransferService, and the real local Postgres (docker-compose) -- no
 * mocked repositories, no Testcontainers. Requires `docker compose up -d` first, same as every
 * other @SpringBootTest in this project (see IdempotencyConcurrencyTest et al.).
 *
 * Tagged "stress" and excluded from the default `./mvnw test` run (see pom.xml) -- run it
 * explicitly with: ./mvnw test -Dgroups=stress -DexcludedGroups=
 *
 * Design notes:
 * - The transfer rate limit (20/min by default, see RateLimitFilter) is raised for this test
 *   context only via a @SpringBootTest property override -- it isn't what's under test here
 *   (RateLimitFilterTest already covers it), and 1,000+ requests from one identity would
 *   otherwise be throttled long before the invariant checks below ever run.
 * - The source account is funded with EXACTLY LOGICAL_TRANSFERS * AMOUNT, no buffer. If
 *   idempotency ever let a retry double-post, the account would run out of funds and a later
 *   attempt would visibly fail (422) rather than the bug hiding behind a merely-wrong balance.
 * - A concurrent race on the SAME Idempotency-Key has exactly one legitimate outcome per this
 *   codebase's own contract (see IdempotencyConcurrencyTest / DepositWithdrawIdempotencyTest):
 *   one winner commits, everyone else either replays the winner's response (2xx, if they land
 *   after the winner's commit) or hits the idempotency_keys unique-constraint race and gets an
 *   unmapped DataIntegrityViolationException -> 500 (if they land concurrently with it). There
 *   is no dedicated 409 mapping for that race today (only for a reused key with a DIFFERENT
 *   body) -- a real rough edge, called out in the report rather than silently worked around,
 *   since fixing it is a production-code change outside this audit's scope.
 * - Every non-2xx response in this test is therefore expected to be transient: retried with the
 *   SAME Idempotency-Key (true idempotent-retry semantics) until it succeeds or a generous
 *   retry budget is exhausted. Exhausting the budget is treated as a genuine failure.
 */
@Tag("stress")
@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = "app.ratelimit.transfer.max-requests=1000000")
class TransferVolumeStressTest {

    private static final int LOGICAL_TRANSFERS = 1000;
    private static final int CONCURRENCY = 16;          // matches Hikari's default pool size (10) closely enough to queue, not fail
    private static final int RACE_EVERY = 20;            // every 20th logical transfer also gets raced
    private static final int RACE_FANOUT = 3;             // concurrent requests sharing that transfer's Idempotency-Key
    private static final int MAX_ATTEMPTS_PER_TRANSFER = 50;
    private static final BigDecimal AMOUNT = new BigDecimal("1.00");
    private static final Path REPORT_PATH = Path.of("docs", "transfer-stress-test-report.md");

    @LocalServerPort int port;

    @Autowired UserRepository users;
    @Autowired AccountRepository accounts;
    @Autowired LedgerEntryRepository ledger;
    @Autowired BalanceService balanceService;
    @Autowired JwtService jwtService;
    @Autowired ObjectMapper objectMapper;

    private final HttpClient http = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build();

    private enum Outcome { SUCCESS, EXPECTED_CONFLICT, GENUINE_FAILURE }

    private record Attempt(int index, boolean raceGroup, int status, Outcome outcome, Long transferId) {}

    private record LogicalResult(int index, boolean raceGroup, Long transferId, List<Attempt> attempts) {}

    @Test
    void thousandTransfersNoDuplicatePostings() throws Exception {
        String runId = UUID.randomUUID().toString().substring(0, 8);

        // --- setup: two real users, two real accounts, source funded exactly once via the
        // service layer directly (not HTTP -- funding isn't the thing under test) ---
        String sourceEmail = "stress-source-" + runId + "@test.local";
        String destEmail = "stress-dest-" + runId + "@test.local";
        Long sourceOwnerId = users.save(new User(sourceEmail, "unused-hash")).getId();
        Long destOwnerId = users.save(new User(destEmail, "unused-hash")).getId();
        Account source = accounts.save(new Account("Stress Source " + runId, "CAD", sourceOwnerId));
        Account dest = accounts.save(new Account("Stress Dest " + runId, "CAD", destOwnerId));

        BigDecimal fundingAmount = AMOUNT.multiply(BigDecimal.valueOf(LOGICAL_TRANSFERS));
        balanceService.deposit(source.getId(), fundingAmount, "stress-fund-" + runId, sourceOwnerId);

        String bearer = "Bearer " + jwtService.generate(sourceOwnerId, sourceEmail, "USER");
        URI transferUri = URI.create("http://localhost:" + port + "/api/transfers");

        // --- run: 1,000 logical transfers, CONCURRENCY workers, every RACE_EVERYth one raced ---
        ConcurrentLinkedQueue<Attempt> attemptLog = new ConcurrentLinkedQueue<>();
        Map<Integer, LogicalResult> results = new ConcurrentHashMap<>();

        ExecutorService pool = Executors.newFixedThreadPool(CONCURRENCY);
        Instant start = Instant.now();

        List<java.util.concurrent.Future<?>> futures = new ArrayList<>();
        for (int i = 1; i <= LOGICAL_TRANSFERS; i++) {
            int index = i;
            futures.add(pool.submit(() -> {
                LogicalResult r = runLogicalTransfer(index, runId, transferUri, bearer, source.getId(), dest.getId(), attemptLog);
                results.put(index, r);
            }));
        }
        for (var f : futures) f.get(120, TimeUnit.SECONDS);
        pool.shutdown();

        Instant end = Instant.now();
        Duration duration = Duration.between(start, end);

        // --- tally ---
        List<Attempt> attempts = new ArrayList<>(attemptLog);
        int totalAttempts = attempts.size();
        long successCount = attempts.stream().filter(a -> a.outcome() == Outcome.SUCCESS).count();
        long expectedConflictCount = attempts.stream().filter(a -> a.outcome() == Outcome.EXPECTED_CONFLICT).count();
        long genuineFailureCount = attempts.stream().filter(a -> a.outcome() == Outcome.GENUINE_FAILURE).count();

        List<Integer> unresolvedIndices = results.values().stream()
                .filter(r -> r.transferId() == null)
                .map(LogicalResult::index)
                .sorted()
                .toList();

        // duplicate-posting check #1: every attempt that returned 2xx for a given logical
        // transfer must have returned the SAME transfer id (idempotent replay, not a new one).
        Map<Integer, Set<Long>> transferIdsSeenPerIndex = new HashMap<>();
        for (Attempt a : attempts) {
            if (a.outcome() == Outcome.SUCCESS) {
                transferIdsSeenPerIndex.computeIfAbsent(a.index(), k -> new HashSet<>()).add(a.transferId());
            }
        }
        List<Integer> indicesWithMultipleTransferIds = transferIdsSeenPerIndex.entrySet().stream()
                .filter(e -> e.getValue().size() > 1)
                .map(Map.Entry::getKey)
                .sorted()
                .toList();

        Set<Long> committedTransferIds = results.values().stream()
                .map(LogicalResult::transferId)
                .filter(java.util.Objects::nonNull)
                .collect(Collectors.toCollection(HashSet::new));

        // duplicate-posting check #2 (authoritative, DB-side): fetch every ledger row tied to
        // one of our transfer ids in a single query, group by transfer id.
        List<LedgerEntry> entries = ledger.findByTransferIdIn(committedTransferIds);
        Map<Long, List<LedgerEntry>> entriesByTransfer = entries.stream()
                .collect(Collectors.groupingBy(LedgerEntry::getTransferId));

        List<Long> transfersWithWrongEntryCount = entriesByTransfer.entrySet().stream()
                .filter(e -> e.getValue().size() != 2)
                .map(Map.Entry::getKey)
                .sorted()
                .toList();

        List<Long> transfersNotBalanced = entriesByTransfer.entrySet().stream()
                .filter(e -> signedSum(e.getValue()).compareTo(BigDecimal.ZERO) != 0)
                .map(Map.Entry::getKey)
                .sorted()
                .toList();

        List<Long> transfersWithoutOneDebitOneCredit = entriesByTransfer.entrySet().stream()
                .filter(e -> e.getValue().stream().filter(en -> en.getEntryType() == EntryType.DEBIT).count() != 1
                        || e.getValue().stream().filter(en -> en.getEntryType() == EntryType.CREDIT).count() != 1)
                .map(Map.Entry::getKey)
                .sorted()
                .toList();

        // balances: fresh accounts, so the ledger-derived balance IS the full expected total --
        // no "before" snapshot needed, and no interference from this repo's pre-existing dev-DB
        // drift on other accounts (see MEMORY: assert per-account, never globally).
        Account sourceAfter = accounts.findById(source.getId()).orElseThrow();
        Account destAfter = accounts.findById(dest.getId()).orElseThrow();
        BigDecimal sourceDerived = ledger.deriveBalance(source.getId());
        BigDecimal destDerived = ledger.deriveBalance(dest.getId());

        BigDecimal expectedSourceBalance = BigDecimal.ZERO.setScale(2);
        BigDecimal expectedDestBalance = fundingAmount.setScale(2);

        boolean sourceBalanceOk = sourceAfter.getBalance().compareTo(expectedSourceBalance) == 0;
        boolean destBalanceOk = destAfter.getBalance().compareTo(expectedDestBalance) == 0;
        boolean sourceLedgerMatchesStoredOk = sourceDerived.compareTo(sourceAfter.getBalance()) == 0;
        boolean destLedgerMatchesStoredOk = destDerived.compareTo(destAfter.getBalance()) == 0;
        boolean noOverdraftOk = sourceAfter.getBalance().compareTo(BigDecimal.ZERO) >= 0
                && destAfter.getBalance().compareTo(BigDecimal.ZERO) >= 0;
        boolean exactlyLogicalCountCommittedOk = committedTransferIds.size() == LOGICAL_TRANSFERS;
        boolean noDuplicatePostingsOk = indicesWithMultipleTransferIds.isEmpty()
                && transfersWithWrongEntryCount.isEmpty();
        boolean everyTransferOneDebitOneCreditOk = transfersWithoutOneDebitOneCredit.isEmpty();
        boolean everyTransferBalancedOk = transfersNotBalanced.isEmpty();
        boolean noGenuineFailuresOk = unresolvedIndices.isEmpty() && genuineFailureCount == 0;

        boolean allPassed = sourceBalanceOk && destBalanceOk && sourceLedgerMatchesStoredOk
                && destLedgerMatchesStoredOk && noOverdraftOk && exactlyLogicalCountCommittedOk
                && noDuplicatePostingsOk && everyTransferOneDebitOneCreditOk && everyTransferBalancedOk
                && noGenuineFailuresOk;

        String gitSha = gitSha();
        String report = buildReport(runId, gitSha, duration, totalAttempts, successCount,
                expectedConflictCount, genuineFailureCount, committedTransferIds.size(),
                indicesWithMultipleTransferIds.size() + transfersWithWrongEntryCount.size(),
                sourceBalanceOk, destBalanceOk, sourceLedgerMatchesStoredOk, destLedgerMatchesStoredOk,
                noOverdraftOk, exactlyLogicalCountCommittedOk, noDuplicatePostingsOk,
                everyTransferOneDebitOneCreditOk, everyTransferBalancedOk, noGenuineFailuresOk,
                allPassed, unresolvedIndices, sourceAfter, destAfter, expectedSourceBalance, expectedDestBalance);
        writeReport(report);

        // --- assertions: fail loudly (and leave the report showing exactly what failed) if any
        // invariant doesn't hold. Nothing here is skipped or softened. ---
        assertThat(unresolvedIndices).as("logical transfers that never succeeded after retrying").isEmpty();
        assertThat(committedTransferIds).as("exactly one committed transfer per logical index").hasSize(LOGICAL_TRANSFERS);
        assertThat(indicesWithMultipleTransferIds).as("logical transfers whose retries returned different transfer ids").isEmpty();
        assertThat(transfersWithWrongEntryCount).as("transfers without exactly 2 ledger entries").isEmpty();
        assertThat(transfersWithoutOneDebitOneCredit).as("transfers without exactly one DEBIT and one CREDIT").isEmpty();
        assertThat(transfersNotBalanced).as("transfers whose ledger entries don't sum to zero").isEmpty();
        assertThat(sourceAfter.getBalance()).as("source account balance").isEqualByComparingTo(expectedSourceBalance);
        assertThat(destAfter.getBalance()).as("destination account balance").isEqualByComparingTo(expectedDestBalance);
        assertThat(sourceDerived).as("source ledger-derived balance vs stored").isEqualByComparingTo(sourceAfter.getBalance());
        assertThat(destDerived).as("destination ledger-derived balance vs stored").isEqualByComparingTo(destAfter.getBalance());
        assertThat(sourceAfter.getBalance()).as("source not overdrawn").isGreaterThanOrEqualTo(BigDecimal.ZERO);
    }

    private LogicalResult runLogicalTransfer(int index, String runId, URI transferUri, String bearer,
                                              Long sourceId, Long destId, ConcurrentLinkedQueue<Attempt> attemptLog) {
        String key = "stress-" + runId + "-" + index;
        boolean raceGroup = index % RACE_EVERY == 0;
        List<Attempt> local = new ArrayList<>();
        Long won = null;

        if (raceGroup) {
            List<Attempt> raceResults = fireRace(index, key, transferUri, bearer, sourceId, destId);
            local.addAll(raceResults);
            for (Attempt a : raceResults) {
                if (a.outcome() == Outcome.SUCCESS) { won = a.transferId(); break; }
            }
        } else {
            Attempt a = fireAttempt(index, key, raceGroup, transferUri, bearer, sourceId, destId);
            local.add(a);
            if (a.outcome() == Outcome.SUCCESS) won = a.transferId();
        }

        int attemptsSoFar = local.size();
        while (won == null && attemptsSoFar < MAX_ATTEMPTS_PER_TRANSFER) {
            attemptsSoFar++;
            sleepJitter();
            Attempt a = fireAttempt(index, key, raceGroup, transferUri, bearer, sourceId, destId);
            local.add(a);
            if (a.outcome() == Outcome.SUCCESS) { won = a.transferId(); }
            else if (a.outcome() == Outcome.GENUINE_FAILURE) { break; } // terminal, non-retryable
        }

        attemptLog.addAll(local);
        return new LogicalResult(index, raceGroup, won, local);
    }

    private List<Attempt> fireRace(int index, String key, URI transferUri, String bearer, Long sourceId, Long destId) {
        CountDownLatch ready = new CountDownLatch(RACE_FANOUT);
        CountDownLatch go = new CountDownLatch(1);
        ConcurrentLinkedQueue<Attempt> raceResults = new ConcurrentLinkedQueue<>();
        List<Thread> threads = new ArrayList<>();

        for (int r = 0; r < RACE_FANOUT; r++) {
            Thread t = Thread.ofVirtual().unstarted(() -> {
                ready.countDown();
                try { go.await(5, TimeUnit.SECONDS); } catch (InterruptedException ignored) {}
                raceResults.add(fireAttempt(index, key, true, transferUri, bearer, sourceId, destId));
            });
            threads.add(t);
            t.start();
        }
        try {
            ready.await(5, TimeUnit.SECONDS);
            go.countDown();
            for (Thread t : threads) t.join(15_000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        return new ArrayList<>(raceResults);
    }

    private Attempt fireAttempt(int index, String key, boolean raceGroup, URI transferUri, String bearer,
                                 Long sourceId, Long destId) {
        try {
            String body = objectMapper.writeValueAsString(new CreateTransferRequest(sourceId, destId, AMOUNT));
            HttpRequest request = HttpRequest.newBuilder(transferUri)
                    .header("Authorization", bearer)
                    .header("Idempotency-Key", key)
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(body))
                    .build();
            HttpResponse<String> response = http.send(request, HttpResponse.BodyHandlers.ofString());
            int status = response.statusCode();

            if (status >= 200 && status < 300) {
                TransferResponse parsed = objectMapper.readValue(response.body(), TransferResponse.class);
                return new Attempt(index, raceGroup, status, Outcome.SUCCESS, parsed.transferId());
            }
            // Only a raw 500 here is the transient DB-race/optimistic-lock shape this test
            // deliberately provokes (see class javadoc) -- retryable with the same key.
            // Anything else (400/403/404/409/422) is a real, non-retryable failure.
            Outcome outcome = status == 500 ? Outcome.EXPECTED_CONFLICT : Outcome.GENUINE_FAILURE;
            return new Attempt(index, raceGroup, status, outcome, null);
        } catch (Exception e) {
            // Network hiccup, interrupted send, or an unparseable 2xx body -- any of these is a
            // genuine failure worth surfacing in the report, not a reason to crash the whole run.
            return new Attempt(index, raceGroup, -1, Outcome.GENUINE_FAILURE, null);
        }
    }

    private void sleepJitter() {
        try {
            Thread.sleep(10 + (long) (Math.random() * 15));
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    private BigDecimal signedSum(List<LedgerEntry> entries) {
        BigDecimal sum = BigDecimal.ZERO;
        for (LedgerEntry e : entries) {
            sum = e.getEntryType() == EntryType.CREDIT ? sum.add(e.getAmount()) : sum.subtract(e.getAmount());
        }
        return sum;
    }

    private String gitSha() {
        try {
            Process p = new ProcessBuilder("git", "rev-parse", "HEAD").start();
            String sha = new String(p.getInputStream().readAllBytes()).trim();
            p.waitFor(5, TimeUnit.SECONDS);
            return sha.isBlank() ? "unknown" : sha;
        } catch (Exception e) {
            return "unknown";
        }
    }

    private void writeReport(String content) {
        try {
            Files.createDirectories(REPORT_PATH.getParent());
            Files.writeString(REPORT_PATH, content);
        } catch (IOException e) {
            throw new java.io.UncheckedIOException("Failed to write stress test report", e);
        }
    }

    private String buildReport(String runId, String gitSha, Duration duration, int totalAttempts,
                                long successCount, long expectedConflictCount, long genuineFailureCount,
                                int committedCount, int duplicatePostingCount,
                                boolean sourceBalanceOk, boolean destBalanceOk,
                                boolean sourceLedgerMatchesStoredOk, boolean destLedgerMatchesStoredOk,
                                boolean noOverdraftOk, boolean exactlyLogicalCountCommittedOk,
                                boolean noDuplicatePostingsOk, boolean everyTransferOneDebitOneCreditOk,
                                boolean everyTransferBalancedOk, boolean noGenuineFailuresOk, boolean allPassed,
                                List<Integer> unresolvedIndices, Account sourceAfter, Account destAfter,
                                BigDecimal expectedSourceBalance, BigDecimal expectedDestBalance) {
        double seconds = duration.toMillis() / 1000.0;
        double throughputLogical = LOGICAL_TRANSFERS / Math.max(seconds, 0.001);
        double throughputAttempts = totalAttempts / Math.max(seconds, 0.001);
        int raceGroups = LOGICAL_TRANSFERS / RACE_EVERY;

        StringBuilder sb = new StringBuilder();
        sb.append("# Transfer volume stress test report\n\n");
        sb.append("Machine-generated by `TransferVolumeStressTest` on every run -- this file is overwritten, not hand-edited. ");
        sb.append("Source: [`src/test/java/com/anish/banking/bank/stress/TransferVolumeStressTest.java`]");
        sb.append("(../src/test/java/com/anish/banking/bank/stress/TransferVolumeStressTest.java).\n\n");
        sb.append("**Result: ").append(allPassed ? "PASS" : "FAIL").append("**\n\n");
        sb.append("| | |\n|---|---|\n");
        sb.append("| Git commit | `").append(gitSha).append("` |\n");
        sb.append("| Date (UTC) | ").append(OffsetDateTime.now(ZoneOffset.UTC)).append(" |\n");
        sb.append("| Run id | `").append(runId).append("` |\n");
        sb.append("| Environment | local, `docker compose up -d` (Postgres 16, Redis 7, Kafka 3.9), Java ")
                .append(System.getProperty("java.version")).append(", ").append(System.getProperty("os.name"))
                .append(" ").append(System.getProperty("os.version")).append(" |\n");
        sb.append("| Concurrency level | ").append(CONCURRENCY).append(" worker threads (fixed pool) |\n");
        sb.append("| Logical transfer count | ").append(LOGICAL_TRANSFERS).append(" |\n");
        sb.append("| Idempotency race groups | ").append(raceGroups).append(" (every ").append(RACE_EVERY)
                .append("th transfer, ").append(RACE_FANOUT).append(" concurrent requests sharing one Idempotency-Key) |\n");
        sb.append("| Total HTTP attempts (incl. retries/races) | ").append(totalAttempts).append(" |\n");
        sb.append("| Successful responses (2xx) | ").append(successCount).append(" |\n");
        sb.append("| Expected transient conflicts (retried) | ").append(expectedConflictCount).append(" |\n");
        sb.append("| Genuine failures | ").append(genuineFailureCount).append(" |\n");
        sb.append("| Duplicate-posting count | ").append(duplicatePostingCount).append(" |\n");
        sb.append("| Duration | ").append(String.format("%.1fs", seconds)).append(" |\n");
        sb.append("| Throughput | ").append(String.format("%.1f logical transfers/s, %.1f HTTP requests/s", throughputLogical, throughputAttempts)).append(" |\n\n");

        sb.append("## Invariant checks\n\n");
        sb.append("| Check | Result |\n|---|---|\n");
        sb.append(row(committedCount + "/" + LOGICAL_TRANSFERS + " logical transfers committed (exactly one each)", exactlyLogicalCountCommittedOk));
        sb.append(row("Every committed transfer has exactly one DEBIT and one CREDIT entry", everyTransferOneDebitOneCreditOk));
        sb.append(row("Every transfer's signed ledger entries sum to zero", everyTransferBalancedOk));
        sb.append(row("No duplicate postings under any Idempotency-Key", noDuplicatePostingsOk));
        sb.append(row("Source balance matches expected (" + expectedSourceBalance + ", actual " + sourceAfter.getBalance() + ")", sourceBalanceOk));
        sb.append(row("Destination balance matches expected (" + expectedDestBalance + ", actual " + destAfter.getBalance() + ")", destBalanceOk));
        sb.append(row("No account overdrawn", noOverdraftOk));
        sb.append(row("Source ledger-derived balance matches stored balance", sourceLedgerMatchesStoredOk));
        sb.append(row("Destination ledger-derived balance matches stored balance", destLedgerMatchesStoredOk));
        sb.append(row("No genuine (non-retryable, unresolved) failures", noGenuineFailuresOk));
        sb.append("\n");

        if (!unresolvedIndices.isEmpty()) {
            sb.append("**Unresolved logical transfer indices:** ").append(unresolvedIndices).append("\n\n");
        }

        sb.append("## How to reproduce\n\n```bash\ndocker compose up -d\n./mvnw test -Dgroups=stress -DexcludedGroups=\n```\n\n");

        sb.append("## Distinguishing expected conflicts from genuine failures\n\n");
        sb.append("Every non-2xx response this test provokes is expected to be a transient race, not a bug: the idempotency-key ")
                .append("race (two requests, same key, landing inside each other's transaction) surfaces today as an unmapped ")
                .append("`DataIntegrityViolationException` -> HTTP 500 (there's no dedicated 409 for this specific race, only for a ")
                .append("reused key with a *different* body -- a rough edge worth knowing about, not fixed here since it's a ")
                .append("production-code change outside this audit's scope). The harness treats any HTTP 500 as retryable with the ")
                .append("SAME Idempotency-Key and keeps retrying (up to ").append(MAX_ATTEMPTS_PER_TRANSFER)
                .append(" attempts) until it sees a 2xx. Any other status (400/403/404/409/422), or exhausting the retry budget, ")
                .append("is counted as a genuine failure -- the table above reports whether any occurred.\n\n");

        sb.append("## Limits of this result\n\n");
        sb.append("This is a reproducible correctness/stress test run against a single local machine and a single-node dev Postgres. ")
                .append("It proves the double-entry and idempotency invariants hold under real concurrent load at this scale and on ")
                .append("this hardware -- it is **not** a production capacity/scalability benchmark (no network latency, no managed-DB ")
                .append("connection limits, no multi-instance contention as in the k3s deployment), and it is **not** a formal proof ")
                .append("(no model checking, no exhaustive interleaving search) -- it's evidence from one, repeatable, adversarial run.\n");

        return sb.toString();
    }

    private String row(String label, boolean ok) {
        return "| " + label + " | " + (ok ? "✅ PASS" : "❌ FAIL") + " |\n";
    }
}
