spring.application.name=bank


spring.datasource.url=jdbc:postgresql://localhost:5433/bank
spring.datasource.username=bank_user
spring.datasource.password=bank_password123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
