
CREATE TABLE reconciliation_breaks (
    id                     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id             BIGINT        NOT NULL REFERENCES account(id),
    ledger_derived_balance NUMERIC(19,2) NOT NULL,
    stored_balance         NUMERIC(19,2) NOT NULL,
    detected_at            TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_reconciliation_breaks_account ON reconciliation_breaks(account_id);
