CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name VARCHAR(120) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'CAD',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE ledger_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT        NOT NULL REFERENCES account(id),
    entry_type  VARCHAR(6)    NOT NULL CHECK (entry_type IN ('DEBIT','CREDIT')),
    amount      NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_ledger_entry_account ON ledger_entry(account_id);