CREATE TABLE transfer (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account_id      BIGINT        NOT NULL REFERENCES account(id),
    destination_account_id BIGINT        NOT NULL REFERENCES account(id),
    amount                 NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    status                 VARCHAR(12)   NOT NULL,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_transfer_distinct CHECK (source_account_id <> destination_account_id)
);

ALTER TABLE ledger_entry ADD COLUMN transfer_id BIGINT REFERENCES transfer(id);
CREATE INDEX idx_ledger_entry_transfer ON ledger_entry(transfer_id);